{{- if not .Values.grafana.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-sight.fullname" . }}-grafana
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "go-sight.labels" . | nindent 4 }}
type: Opaque
data:
  GF_SECURITY_ADMIN_USER: {{ .Values.grafana.adminUser | b64enc }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.grafana.adminPassword | b64enc }}
  GF_DATABASE_NAME: {{ .Values.postgres.credentials.database | b64enc }}
  GF_DATABASE_USER: {{ .Values.postgres.credentials.user | b64enc }}
  GF_DATABASE_PASSWORD: {{ .Values.postgres.credentials.password | b64enc }}
{{- end }}
