{{- if not .Values.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-sight.fullname" . }}-postgres
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "go-sight.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.credentials.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password | b64enc }}
  POSTGRES_DB: {{ .Values.postgres.credentials.database | b64enc }}
{{- end }}
